#/**
#* Title: Algorithm analysis & Sorting
#* Author : Name & Surname
#* ID: 12345678
#* Section : 1
#* Homework : 1
#* Description : description of your code */

hw1: 22101782_yasemin_akin_hw1.o sorting.o
	g++ 22101782_yasemin_akin_hw1.o sorting.o -o hw1

22101782_yasemin_akin_hw1.o: 22101782_yasemin_akin_hw1.cpp
	g++ -c 22101782_yasemin_akin_hw1.cpp

sorting.o: sorting.cpp sorting.h
	g++ -c sorting.cpp

clean:
	rm *.o hw1
